package griffith;

import org.junit.jupiter.api.Test;

import Sprites.Food;
import Sprites.Player;
import game.GameManager;

import static org.junit.Assert.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

import java.lang.reflect.Field;
import java.util.ArrayList;

import javax.swing.Timer;

public class TestTimer {
    GameManager game;
    ArrayList<String> selectedCharacters;

    @Test
    public void testTimerDecreases() throws InterruptedException {
        // Initialise a new GameManager object.
        game = new GameManager();

        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Get the current timer.
        String currentTimer = game.getTimer();

        // Wait 1 second.
        Thread.sleep(1000);

        // Get the timer after 1 second.
        String updatedTimer = game.getTimer();

        // Check thet the timer decreased.
        assertNotEquals(currentTimer, updatedTimer);
    }

    @Test
    public void testInitialiseTimer()
            throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        // Initialise a new GameManager object.
        game = new GameManager();

        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Actual values.
        int actualMinute = game.getMinute();
        int actualSecond = game.getSecond();

        // Expected values.
        int expectedMinute = 2;
        int expectedSecond = 0;

        // Check if the expected values are the same as the ones generated by the timer
        // methods.
        assertEquals(expectedMinute, actualMinute);
        assertEquals(expectedSecond, actualSecond);
    }

    @Test
    public void testTimerRunning()
            throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        // Initialise a new GameManager object.
        game = new GameManager();

        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Access the timer field.
        // https://www.concretepage.com/java/java-reflection-access-private-fields-methods-constructors
        Field timerField = GameManager.class.getDeclaredField("timer");
        timerField.setAccessible(true);
        Timer timer = (Timer) timerField.get(game);

        // Check if the timer isn't empty.
        assertNotNull(timer);

        // Check if the timer is running.
        assertTrue(timer.isRunning());
    }

    @Test
    public void testStopTimer() throws InterruptedException {
        // Initialise a new GameManager object.
        game = new GameManager();

        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Store the value of the timer before its stoped.
        String timerBeforeStop = game.getTimer();

        // Stop the timer.
        game.stopTimer();

        // Wait 0.2 seconds.
        Thread.sleep(200);

        // Then store the value after the timer was toped.
        String timerAfterStop = game.getTimer();
        // Check if the timer stoped.
        assertEquals(timerBeforeStop, timerAfterStop);
    }

    @Test
    public void testTimerFormatting() {
        // Initialise a new GameManager object.
        game = new GameManager();

        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Get the timer.
        String timer = game.getTimer();

        // Check that the timer is formated properly.
        assertTrue(timer.matches("\\d{2}:\\d{2}"));
    }

    // test if timer subtracts 20 seconds after collecting food with type: FAST_TIMER
    @Test
    public void testTimerReducesSeconds() {
        GameManager gm = new GameManager();
        
        Food food = new Food("cabage.png", 100, 100, 60, 60, Food.FoodType.FAST_TIMER);
        Player player = new Player("box turtle.png", 100, 100, 90, 90);
        gm.checkCollision(player, food);
    
        //test if collision happened
        assertTrue("Collision was not detected", food.isCollected());
        
        //check if time changed
        assertEquals(1, gm.getMinute());
        assertEquals(40, gm.getSecond());
    }
}