package griffith;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

import org.junit.Test;

import Sprites.CheckPoint;
import Sprites.Player;
import constants.Constants;
import game.GameManager;
import riddles.Riddle;
import riddles.RiddleData;

public class TestGameManager {
//PlayerMovement class Test
	@Test 
	public void testPlayerMoveLeft() {
		Player player=new Player(null,5,3, 0, 0);
		int actual=player.moveLeft();
		assertEquals(4,actual);
	}
	@Test
	public void testPlayerMoveRight() {
		Player player=new Player(null,6,6, 0, 0);
		int actual=player.moveRight();
		assertEquals(7,actual);
	}
	@Test
	public void testPlayerJump() {
		Player player=new Player(null,20,40,0,0);
		player.jump();
		assertEquals(40-Constants.PLAYER_JUMP_HEIGHT,player.getY());
	}
	@Test
	public void testUpdateDirectionIs1() {
		Player player=new Player(null,20,40,0,0);
		player.setDirection(1);
		player.update();
		assertEquals(21,player.getX());
	}
	@Test
	public void testUpdateDirection() {
		Player player=new Player(null,20,40,0,0);
		player.setDirection(-1);
		player.update();
		assertEquals(19,player.getX());
	}
	@Test
	public void testPlayerFallsInAir() {
		Player player=new Player(null,50,40,0,0);
		int beforeY=player.getY();//players current position
		player.update();
		assertEquals(beforeY+Constants.PLAYER_FALL_SPEED,player.getY());	
	}
	
    // Riddle Class Tests
    @Test
    public void testCheckAnswer() {
        // Initialise the riddle class.
        Riddle riddle = new Riddle("I can smell food from a mile away.", "Bear",
                "In winter I go into a deep sleep called hibernation.");

        // Actual values generated when we run the checkAnswer method.
        boolean actual = riddle.checkAnswer(" Bear ");
        boolean actual1 = riddle.checkAnswer("bear");
        boolean actual2 = riddle.checkAnswer("");
        boolean actual3 = riddle.checkAnswer("hair");

        // Test the values generated by running the checkAnswer method.
        assertTrue(actual);
        assertTrue(actual1);
        assertFalse(actual2);
        assertFalse(actual3);

        // Test for the NullPointerException.
        Exception exception = assertThrows(NullPointerException.class, () -> {
            riddle.checkAnswer(null);
        });
        String expectedMessage = "null";

        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }

    @Test
    public void testIncrementAttempt() {
        // Initialise the riddle class.
        Riddle riddle = new Riddle("I can smell food from a mile away.", "Bear",
                "In winter I go into a deep sleep called hibernation.");

        // Check that the counter starts from zero in the begining.
        int expected = 0;
        int actual = riddle.getCountAttempts();
        assertEquals(expected, actual);

        // Increase the counter.
        riddle.incrementAttempt();
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        // Check if the counter increases correctly.
        int expected1 = 3;
        int actual1 = riddle.getCountAttempts();

        assertEquals(expected1, actual1);
    }

    @Test
    public void testAttemptsFinished() {
        // Initialise the riddle class.
        Riddle riddle = new Riddle("I can smell food from a mile away.", "Bear",
                "In winter I go into a deep sleep called hibernation.");

        // Increase the number of attempts.
        riddle.incrementAttempt();
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        // Check if the user has finished all their attempts.
        boolean actual = riddle.attemptsFinished();
        boolean expected = false;
        assertEquals(expected, actual);

        // Increase the attempts counter.
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        // Check if the attempts have finished.
        boolean actual1 = riddle.attemptsFinished();
        boolean expected1 = true;

        assertEquals(expected1, actual1);

        // Increase the attempts counter.
        riddle.incrementAttempt();

        // Check if the attempts have finished.
        boolean actual2 = riddle.attemptsFinished();
        boolean expected2 = true;

        assertEquals(expected2, actual2);
    }

    @Test
    public void testDisplayHint() {
        // Initialise the riddle class.
        Riddle riddle = new Riddle("I can smell food from a mile away.", "Bear",
                "In winter I go into a deep sleep called hibernation.");

        // Test the displayHint method before the treshold when the hint is going to apear is reached.
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        String actual = riddle.displayHint();
        String expected = "";

        assertEquals(expected, actual);

        // Test the displayHint method at the treshold when the hint is going to apear.
        riddle.incrementAttempt();

        String actual1 = riddle.displayHint();
        String expected1 = "In winter I go into a deep sleep called hibernation.";

        assertEquals(expected1, actual1);
        
        // Test the displayHint method after the treshold when the hint is going to apear is reached.
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        String actual2 = riddle.displayHint();
        String expected2 = "In winter I go into a deep sleep called hibernation.";

        assertEquals(expected2, actual2);

    }

    @Test
    public void testIsHintDisplayed(){
        // Initialise the riddle class.
        Riddle riddle = new Riddle("I can smell food from a mile away.", "Bear",
                "In winter I go into a deep sleep called hibernation.");

        // Test that the hint is hiden in the begining.
        boolean actual = riddle.isHintDisplayed();
        
        assertFalse(actual);

        // Test that the hint is hiden if the treshold hasn't been reached.
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        boolean actual1 = riddle.isHintDisplayed();
        
        assertFalse(actual1);



        // Test that the hint is shown when the treshold is reached.
        riddle.incrementAttempt();
        riddle.incrementAttempt();
        riddle.incrementAttempt();

        riddle.displayHint();

        boolean actual2 = riddle.isHintDisplayed();

        assertTrue(actual2);
    }

    // Test correct answer
    @Test
    public void testCorrectAnswer() {
        Riddle r = new Riddle("Q", "Dog", "Hint");
        CheckPoint cp = new CheckPoint("x.png", 0, 0, 10, 10, r);
        assertTrue(cp.attempt("dog"));
    }

    // Test wrong answer(Checkpoint)
    @Test
    public void testWrongAnswer() {
        Riddle r = new Riddle("Q", "Dog", "Hint");
        CheckPoint cp = new CheckPoint("x.png", 0, 0, 10, 10, r);
        assertFalse(cp.attempt("cat"));
    }

    // Test max attempts = 5
    @Test
    public void testMaxAttempts() {
        Riddle r = new Riddle("Q", "Dog", "Hint");
        CheckPoint cp = new CheckPoint("x.png", 0, 0, 10, 10, r);
        for (int i = 0; i < 5; i++) {
            cp.attempt("wrong");
        }

        assertTrue(cp.isFailed());
    }

    // Test hint after 3 attempts
    @Test
    public void testHintAfterThreeAttempts() {
        Riddle r = new Riddle("Q", "Dog", "Hint");
        CheckPoint cp = new CheckPoint("x.png", 0, 0, 10, 10, r);

        cp.attempt("a");
        cp.attempt("b");
        cp.attempt("c");

        assertEquals("Hint", cp.getHint());
    }

    @Test
    public void testGetRiddleByIndex(){
        RiddleData data = new RiddleData();
        Riddle result = data.getRiddlesByIndex(0);
        assertNotNull(result);

        int total = data.getRiddles().size();
        result = data.getRiddlesByIndex(total-1);
        assertNotNull(result);
        
        result = data.getRiddlesByIndex(-5);
        assertNull(result);
       
        result = data.getRiddlesByIndex(total);
        assertNull(result);
    }

}
