package griffith;

import org.junit.jupiter.api.Test;

import game.GameManager;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Field;
import java.util.ArrayList;

import javax.swing.Timer;

import static org.junit.Assert.assertEquals;

public class TestTimer {
    GameManager game;
    ArrayList<String> selectedCharacters;

    @Test
    public void testInitialiseTimer() throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        // Initialise a new GameManager object.
        game = new GameManager();
        
        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Actual values.
        int actualMinute = game.getMinute();
        int actualSecond = game.getSecond();

        // Expected values.
        int expectedMinute = 2;
        int expectedSecond = 0;

        // Check if the expected values are the same as the ones generated by the timer methods.
        assertEquals(expectedMinute, actualMinute);
        assertEquals(expectedSecond, actualSecond);
    }

    @Test
    public void testTimerRunning() throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        // Initialise a new GameManager object.
        game = new GameManager();
        
        // List to add characters so we can initialise the game.
        selectedCharacters = new ArrayList<String>();

        // Add characters to the list.
        selectedCharacters.add("Box Turtle");
        selectedCharacters.add("Kakapo");

        // Initialise the game with characters.
        game.initializeGame(selectedCharacters);

        // Access the timer field.
        Field timerField = GameManager.class.getDeclaredField("timer");
        timerField.setAccessible(true);
        Timer timer = (Timer) timerField.get(game);

        // Check if the timer isn't empty.
        assertNotNull(timer);

        // Check if the timer is running.
        assertTrue(timer.isRunning());
    }
}
