package griffith;

import org.junit.jupiter.api.Test;

import game.GameManager;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Field;
import java.util.ArrayList;

import javax.swing.Timer;

import static org.junit.Assert.assertEquals;


public class TestTimer {
    GameManager game;

    @Test
    public void testInitialiseTimer() throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        // Create a new GameManager object.
        game = new GameManager();

        // Initialise the game with characters.
        ArrayList<String> characters = new ArrayList<String>();
        characters.add("Box Turtle");
        characters.add("Lemur");
        game.initializeGame(characters);

        // Actual values.
        int actualMinute = game.getMinute();
        int actualSecond = game.getSecond();

        // Expected values.
        int expectedMinute = 2;
        int expectedSecond = 0;

        // Check if the expected values are the same as the ones generated by the timer methods.
        assertEquals(expectedMinute, actualMinute);
        assertEquals(expectedSecond,actualSecond);
    }

    @Test
    public void testTimerRunning() throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
       // Create a new GameManager object.
        game = new GameManager();

        // Initialise the game with characters.
        ArrayList<String> characters = new ArrayList<String>();
        characters.add("Box Turtle");
        characters.add("Lemur");
        game.initializeGame(characters);

        // Access the timer field.
        Field timerField = GameManager.class.getDeclaredField("timer");
        timerField.setAccessible(true);
        Timer timer = (Timer) timerField.get(game);

        // Check if the timer isn't empty.
        assertNotNull(timer);

        // Check if the timer is running.
        assertTrue(timer.isRunning());
    }
}
